### ISSUE TITLE
Loading dirty-chai before chai-jquery breaks empty()

### ISSUE THREAD

**Issue by justin-lau** [prodatakey/dirty-chai#11]
The [readme](https://github.com/prodatakey/dirty-chai#plugin-assertions) stated that dirty-chai should be loaded before any other plugins, but I found that if I load dirty-chai before [chai-jquery](https://github.com/chaijs/chai-jquery), a `should.be.empty()` throws a `TypeError: empty is not a function`.

However, if I load chai-jquery before dirty-chai, the said problem is gone, and what's more, the property assertions in chai-jquery actually convert to method assertions.

**Comment by andreypechkurov** [comment]
I've found that the same stays true for [chai-as-promised](https://github.com/domenic/chai-as-promised) library. You have to load it before dirty-chai or otherwise it's broken.

**Comment by astorije** [comment]
FWIW, while using [the `chai-immutable` plugin](https://github.com/astorije/chai-immutable), @iensu noticed the similar requirement: https://github.com/astorije/chai-immutable/issues/57.

**Comment by joshperry** [comment]
Sorry guys, dirty-chai does hook the internal methods that plugins use to extend chai in order to convert assertions to methods. I do have an outstanding PR with tests that work a problem with a similar issue to this. Perhaps the guidance should just be changed to run dirty-chai last instead of first.

Hopefully this will get less hairy with extendable assertion formats that are supposed to come in a newer chai. I'll be tracking this in #7.

**Comment by adamcohen** [comment]
I'm running into the same issue with [chai-fs](https://github.com/chaijs/chai-fs), although I can't fix the  `TypeError: expect(...).to.be.empty is not a function` error regardless of the order.

I've tried every permutation of the following lines, but nothing works:

```javascript
const chaiFS = require('chai-fs')
const dirtyChai = require('dirty-chai')

chai.use(dirtyChai)
chai.use(chaiFS)
```

It seems that once you use `chai.use(chaiFS)` in one of your tests, any other test that uses `to.be.empty()` will fail.

I've gotten around this by using the property form of `empty` instead of the function form, and just disabling the eslint rule wherever I do this, but it's far from ideal:

```
// eslint-disable-next-line no-unused-expressions
 expect(subject).to.be.empty
```
