### ISSUE TITLE
dirty-chai breaks chai-as-promised eventually.equal

### ISSUE THREAD

**Issue by leedm777** [prodatakey/dirty-chai#4]
`dirty-chai` interferes with `chai-as-promised`; specifically the `eventually.equal` call chain.

The following code demonstrates the problem.

```
cat <<EOF > package.json
{
  "name": "dirty-chai-as-promised",
  "version": "1.0.0",
  "description": "Testing chai-as-promised with dirty-chai",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "David M. Lee, II",
  "license": "ISC",
  "dependencies": {
    "chai": "^2.0.0",
    "chai-as-promised": "^4.2.0",
    "dirty-chai": "^1.0.1",
    "es6-promise": "^2.0.1",
    "mocha": "^2.1.0"
  }
}
EOF

mkdir test
cat <<EOF > test/test.js
require('es6-promise').polyfill();

var chai = require('chai');
var should = chai.should();

// comment the following line to get the test to pass
chai.use(require('dirty-chai'));
chai.use(require('chai-as-promised'));

describe('some test', function () {
  // erroneously fails with expected { Object (_id, _state, ...) } to equal 'hi'
  it('resolved should resolve', function () {
    return Promise.resolve('hi').should.eventually.equal('hi');
  });
});
EOF

npm i
npm test
```

**Comment by joshperry** [comment]
Yeah, interesting. Good catch. Looks like `chai-as-promised` is doing something very similar to `dirty-chai`. It shouldn't have conflicted, but my plugin was processing some of the deferred assertions in the proper order or passing the proper context.

Let me write up some regression tests and I'll push out a fix.

**Comment by joshperry** [comment]
@leedm777 I think I got this working. The interactions between dirty-chai and chai-as-promised is a little hinky because both of these plug-ins are attempting to hook assertions in order to defer them.

This won't work with the currently published chai-as-promised, but I did write a PR in domenic/chai-as-promised#87 to fix this. I don't think Domenic likes me so I'm not sure if he'll merge the change or not. Sorry.

At this point I'm wondering if:
a. I should give up on this because Domenic has a lot more pull in the chai community and is pretty dead-set against this feature.
b. I should make dirty-chai a full fork of chai and add this functionality natively without all this deferral nonsense.

**Comment by fluky** [comment]
I vote for b.  I'd feel much more comfortable with a product that is maintained by you.  The whole discussion on getters with side effects gives me the willies about using chai at all.

**Comment by hontas** [comment]
So the PR got merged in chai-as-promised but I'm still getting the same error.. using chai-as-promise 5.3.0 and dirty-chai 1.2.2. You get the same?

**Comment by alexlukelevy** [comment]
I managed to fix this by ensuring I register chai-as-promised before dirty-chai.
